### ISSUE TITLE
Wrong parameters?

### ISSUE THREAD

**Issue by qianl15** [jdellithorpe/cloudlab-generic-profile#1]
In `system-setup.sh`, should [line 21](https://github.com/jdellithorpe/cloudlab-generic-profile/blob/f816a6b318328d9dedced02f02b9acb9b65a5ac7/system-setup.sh#L21) and [line 23](https://github.com/jdellithorpe/cloudlab-generic-profile/blob/f816a6b318328d9dedced02f02b9acb9b65a5ac7/system-setup.sh#L23) be `$3` and `$4`, respectively?

**Comment by qianl15** [comment]
By the way, we may also need to add the code to install `maven` in `system-setup.sh`, because I saw the use of `mvn` in user setup script.

**Comment by jdellithorpe** [comment]
Fixed issue in 80223c2

**Comment by jdellithorpe** [comment]
Also, I deleted everything in the `user-setup.sh` script (that was accidentally left there when I did the initial commit), so maven should no longer be necessary. The `user-setup.sh` script can be used to put whatever you want in there now.
